#!/bin/bash
####################################
#####
###
##
#
#
# Startup Script for the Application
####################################
echo "Destroying [SampleApp]"
docker stop photoprism
docker rm photoprism

