#!/bin/bash
####################################
#####
###
##
#
#
# Startup Script for the Application
####################################


if [ $(docker ps -q -f name=photoprism) ]
then
  # Photoprism is running
  echo "[SampleApp] is already running..."
   exit 1
fi
echo "Starting [SampleApp]"
docker start photoprism
