#!/bin/bash
####################################
#####
###
##
#
#
# Startup Script for the Application
####################################
set -e

echo "Stopping [SampleApp]"

docker start photoprism
