#!/bin/bash
####################################
#####
###
##
#
#
# Startup Script for the Application
####################################
echo "Stopping [SampleApp]"

docker stop photoprism
#docker rm photoprism

